name: complex_ui_openai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.2.0
  fl_chart: ^0.70.2
  window_size: ^0.1.0
  provider: ^6.0.5
  freezed_annotation: ^3.1.0
  path_provider: ^2.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.2
  google_fonts: ^6.3.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  freezed: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - l10n/app_en.arb
    - l10n/app_tr.arb
    # Icons and other SVGs
    - assets/icons/
